export const POLICY_REASONS = Object.freeze({
  EMPTY_KEEP: 'The column is empty, so retaining emptiness adds no source disclosure.',
  LOW_RISK_KEEP: 'The field is low risk and useful to preserve as a test control.',
  DIRECT_REPLACE: 'Direct identifiers must be replaced before a safe test dataset is produced.',
  ID_PATTERN: 'Identifier structure is useful for tests, but original identifiers must not be copied.',
  LOCATION_REPLACE: 'Location values can identify someone when combined with other fields, so replace this column independently. Generated placeholders are synthetic labels, not claims of a real or coherent location. No relationship with other location columns is assumed unless one is explicitly configured.',
  ORGANISATION_NAME_REPLACE: 'This looks like an organisation or service-location name, so generate a readable fictional organisation instead of copying the source.',
  DATE_SHIFT: 'Date ordering can be useful while exact source dates should be shifted.',
  CATEGORY_RESAMPLE: 'Category distribution is useful, but output should be resampled rather than copied row-for-row.',
  OPERATIONAL_VOCABULARY_RESAMPLE: 'This looks like a bounded business vocabulary, so reuse its valid choices and distribution instead of inventing invalid labels.',
  MIXED_OPERATIONAL_TEXT_REPLACE: 'This field mixes normal business labels with longer free-form values, so replace it rather than resampling unusual source text.',
  ORDINARY_TEXT_REPLACE: 'No special privacy role was detected, but the values are not a bounded vocabulary that can be safely reused; generate replacement text instead of copying source values.',
  STRUCTURED_REFERENCE_PATTERN: 'This looks like a business reference or catalog code, so generate new values in the same structural style instead of copying source values.',
  STRONG_UNLABELLED_PATTERN: 'The values have a strong repeated code-like shape even without a useful header, so regenerate that shape instead of treating them as free text.',
  CONSTANT_REPLACE: 'The column has a single non-empty source value, so replace it consistently with one synthetic value instead of retaining or redistributing the original constant.',
  HIGH_RISK_CATEGORY_REPLACE: 'This category may contain identifying names or labels, so replace each distinct value consistently instead of reusing its source vocabulary.',
  CATEGORY_GENERALISE: 'Rare or identifying categories should be generalised before reuse.',
  NUMERIC_RESAMPLE: 'Numeric ranges are useful for tests, but exact row values need not be preserved.',
  ROLE_QUASI_GENERALISE: 'This field can identify a person when combined with other fields, so reduce its detail instead of keeping an exact-looking value.',
  ROLE_SENSITIVE_GENERALISE: 'This sensitive field should keep only a broader testing group, not the original detailed category or date.',
  ROLE_SENSITIVE_RESAMPLE: 'This sensitive field can keep a useful overall distribution without copying values row-for-row.',
  ROLE_DIRECT_REPLACE: 'This field can directly identify or consistently single out a record, so replace its source value.',
  FREE_TEXT_SANITISE: 'Free text can hide identifiers and must be sanitised before use.',
  TEMPORAL_REVIEW_KEEP: 'The values look like dates or times, but their representation is not safely supported; keep them unchanged for explicit review instead of deleting them automatically.',
  UNKNOWN_CLEAR: 'Unknown or low-confidence content is cleared until a user reviews it.',
  FULL_SYNTHETIC: 'Full synthetic mode replaces or resamples every non-empty source field.',
});
